language: python

sudo: false

python:
- 2.7

before_install:
 # download and install miniconda
 - wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh;
 - bash miniconda.sh -b -p $HOME/conda
 - export PATH="$HOME/conda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 # Useful for debugging any issues with conda
 - conda info -a

 # create and activate the build/test environment
 - conda create -q -n babyshortener python=2.7.13
 - source activate babyshortener

install:
  - pip install .
  - pip install -r requirements.txt

script:
- python tests/test_shortener.py